##
## Makefile
##
## Made by Jesper Louis Andersen
## Login   <jlouissuccubus.local.domain>
##
## Started on  Wed Jul  4 16:32:07 2007 Jesper Louis Andersen
## Last update Wed Jul  4 16:32:07 2007 Jesper Louis Andersen
##

.PHONY: all

all:
	pdflatex documentation.tex